#!/usr/bin/env python3
"""emit_traces.py — the Python->JSON boundary of the walking skeleton.

Runs the REAL certifying solver (src/solver.py) over each fixture in
fixtures.json and writes traces.json = { id: {label, intended, status,
result} }, where `result` is SolveResult.to_dict() (the grid consumes THIS,
never Python). No solving logic lives here — this only serializes the engine's
own output, so the grid renders verified solver state, not a re-implementation.

Run:  python3 emit_traces.py   (from projects/loop-sudoku/app/)
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.abspath(os.path.join(HERE, "..", "src"))
sys.path.insert(0, SRC)

from solver import solve, from_string  # noqa: E402
from faces import all_faces  # noqa: E402  (Block C: four folds of the trace)


def main() -> int:
    with open(os.path.join(HERE, "fixtures.json")) as f:
        fixtures = json.load(f)

    out = {"_note": "Generated by emit_traces.py — solver output, do not hand-edit.",
           "puzzles": []}
    for p in fixtures["puzzles"]:
        givens_str = p["givens"]
        entry = {"id": p["id"], "label": p["label"],
                 "intended": p.get("intended", "")}
        if len(givens_str) != 81:
            entry["error"] = f"givens is {len(givens_str)} chars, expected 81"
            out["puzzles"].append(entry)
            print(f"  SKIP {p['id']}: {entry['error']}")
            continue
        grid = from_string(givens_str)
        res = solve(grid)
        entry["givens"] = givens_str
        entry["result"] = res.to_dict()  # {status, trace, solution}
        entry["faces"] = all_faces(res)   # grade/hint/teach/validate — folds only
        entry["status"] = res.status
        entry["steps"] = len(res.trace)
        out["puzzles"].append(entry)
        print(f"  ok   {p['id']:14s} -> {res.status:14s} ({len(res.trace)} steps)")

    with open(os.path.join(HERE, "traces.json"), "w") as f:
        json.dump(out, f, indent=2)
    # Also emit a JS global so index.html opens by double-click (no server / no
    # file:// fetch/CORS). traces.json stays the canonical machine-readable copy.
    with open(os.path.join(HERE, "traces.js"), "w") as f:
        f.write("window.TRACES = ")
        json.dump(out, f, indent=2)
        f.write(";\n")
    print(f"\nwrote traces.json + traces.js ({len(out['puzzles'])} puzzles)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
